# Generated by Django 5.1.4 on 2024-12-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='operation_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw')], default='deposit', max_length=32, verbose_name='Operation type'),
            preserve_default=False,
        ),
    ]
